NAME		:= user
X_INCDIRS	+= $(src)/libc/include $(src)/libx/include
SRC			= *.S *.c libm/ libx/ libc/string/ libc/stdio/ libc/stdlib/ libc/ctype/ libc/errno/ libc/malloc/ libc/exit/

TARGET_TYPE	:= static