#pragma once
#define __NR_ni_syscall 0
#define __NR_console_putc 1
#define __NR_console_puts 2
#define __NR_process_create 3
#define __NR_process_exit 4
#define __NR_thread_create 5
#define __NR_thread_exit 6
#define __NR_vmo_create 7
#define __NR_vmo_write 8
#define __NR_vmo_read 9
#define __NR_vmo_map 10
#define __NR_register_server 11
#define __NR_register_named_server 12
#define __NR_register_client 13
#define __NR_register_client_by_name 14
#define __NR_ipc_call 15
#define __NR_ipc_return 16
#define __NR_nanosleep 17
#define __NR_clock_get 18
#define __NR_clock_get_monotonic 19
#define __NR_ticks_get 20
#define __NR_ticks_per_second 21
#define __NR_deadline_after 22
#define __NR_yield 23
#define __NR_futex_wait 24
#define __NR_futex_wake 25
#define __NR_block_read 26
#define __NR_block_write 27
#define __NR_block_capacity 28
#define __NR_block_size 29
#define __NR_block_count 30
#define __NR_syscalls 31

#ifdef SYSCALL_IMPL

extern void sys_ni_syscall();
extern void sys_console_putc();
extern void sys_console_puts();
extern void sys_process_create();
extern void sys_process_exit();
extern void sys_thread_create();
extern void sys_thread_exit();
extern void sys_vmo_create();
extern void sys_vmo_write();
extern void sys_vmo_read();
extern void sys_vmo_map();
extern void sys_register_server();
extern void sys_register_named_server();
extern void sys_register_client();
extern void sys_register_client_by_name();
extern void sys_ipc_call();
extern void sys_ipc_return();
extern void sys_nanosleep();
extern void sys_clock_get();
extern void sys_clock_get_monotonic();
extern void sys_ticks_get();
extern void sys_ticks_per_second();
extern void sys_deadline_after();
extern void sys_yield();
extern void sys_futex_wait();
extern void sys_futex_wake();
extern void sys_block_read();
extern void sys_block_write();
extern void sys_block_capacity();
extern void sys_block_size();
extern void sys_block_count();

void *sys_call_table[__NR_syscalls] = {
	[__NR_ni_syscall] = sys_ni_syscall,
	[__NR_console_putc] = sys_console_putc,
	[__NR_console_puts] = sys_console_puts,
	[__NR_process_create] = sys_process_create,
	[__NR_process_exit] = sys_process_exit,
	[__NR_thread_create] = sys_thread_create,
	[__NR_thread_exit] = sys_thread_exit,
	[__NR_vmo_create] = sys_vmo_create,
	[__NR_vmo_write] = sys_vmo_write,
	[__NR_vmo_read] = sys_vmo_read,
	[__NR_vmo_map] = sys_vmo_map,
	[__NR_register_server] = sys_register_server,
	[__NR_register_named_server] = sys_register_named_server,
	[__NR_register_client] = sys_register_client,
	[__NR_register_client_by_name] = sys_register_client_by_name,
	[__NR_ipc_call] = sys_ipc_call,
	[__NR_ipc_return] = sys_ipc_return,
	[__NR_nanosleep] = sys_nanosleep,
	[__NR_clock_get] = sys_clock_get,
	[__NR_clock_get_monotonic] = sys_clock_get_monotonic,
	[__NR_ticks_get] = sys_ticks_get,
	[__NR_ticks_per_second] = sys_ticks_per_second,
	[__NR_deadline_after] = sys_deadline_after,
	[__NR_yield] = sys_yield,
	[__NR_futex_wait] = sys_futex_wait,
	[__NR_futex_wake] = sys_futex_wake,
	[__NR_block_read] = sys_block_read,
	[__NR_block_write] = sys_block_write,
	[__NR_block_capacity] = sys_block_capacity,
	[__NR_block_size] = sys_block_size,
	[__NR_block_count] = sys_block_count,
};
#endif
